#coding:utf-8
#----------------------------------------------------------------------
# This file was generated by encode_bitmaps.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

#----------------------------------------------------------------------
_book_red = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAApVJ"
    "REFUOI2Fk09IFHEUxz+/mdmdddddd7Usc/2LYoSWsbVqWIfoIEgQUd2yTt4ju3SocxBdO3Qq"
    "6BAEUVFRJCGBWaQZ/gs127RyXV1T193ZndmZ6dAallZfePAO733gve97gn9LrMvt/xWIyyBO"
    "VFAnUoRtD/vdW/yhlKbrnSOpjlcQBTIbAKkGDtp5ol0u8O8Tqjtkuz1+NT8PLAucKmQ1Hj8f"
    "fXps2r5gwPifEPlSqLRPKalsc+4NVcuW7cqW1mCU1GDuPoTZeBhFT1MrrdYE55Z89zXeAyuA"
    "9QtwPujoUgu8+VlDIGcSJMLtSEXbkPLyUUwDSXXB7AS7A44GZXrFeGEyCiTXIPJZR7q1uK5s"
    "Z+LjNK6S7SjRCHL0M+pAN1LfExh9C0YGyamIRp8jvPg1Nd9vMwmkAFtuMpnf5dBPu4PFIrGY"
    "wp2OI8fnwNBBkn/u2bLANHDlC6lJyraMzJtTkxABNKljmddjkwv3hJ0hvfAdPAGwLTBNMA3I"
    "apBcYnV8jpHeGIMle9ymEPVAFeBUAO1RlCvlQ1/aixurXEuRGH6vDrMLRKMmo4WlTFW0YJxp"
    "xRVuIVhepj2rq1YBDyApgHUxy3D9p+Sto+Wxzp5IkoXgTpaaT6HvDePz+/F5vRR6PLi9frbK"
    "dl5XMc6rMTTAUnJupO8sc620O3byRtvxQFnoALWVFRT5CgiILDVf37F17A0F/T1a//S3QWEC"
    "4AfUNYB9GyJHUlyvtNMXG1cmaO59SWB4wE5OzIzfjfPhoUF8wMLUbZaBmZyV9m+nvAd2nHPx"
    "QBdkbmpMDkFmBdJADPiSi1lgGUgAq+sBAA6gGmgF3Oua4sBqzvs0YJJ7rj8BACoQAKRcgwbo"
    "a6NuUr+pxF/gG/QDEGYH9mMazfQAAAAASUVORK5CYII=")

#----------------------------------------------------------------------
_book_green = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAopJ"
    "REFUOI2Nk0tPEwEUhb+ZQgeYtrQ8lPAsTwkREgJUUKLooibEhSG60YWu/AWGhb/AjSvjxr0m"
    "bn0gC6MkoBgCATGCsVILyMOW8ui0006nM+NmICjxcVY3ufd+yc05V+DvEg7V1r8GBK4i0kUr"
    "CgGhkJ6KMrkrmdJV5UH2BmF+ANpRwGMuYDBY6fJ0+wRnZ6kkebwuJ5qaxZF1ocsZxp4vv9Tv"
    "M4xO6HeI49yt+rnGQv/5YEOt34jnS3WOVqrMNk5VBDldFSS+twXVieYNKeVmlg+AApgHgLJL"
    "8p36Go8Ujwukswku+i9TWlyOLLlI51LITplwcgHZX9ARs1SdBRaB1D7EobZrA4N9zY0Toe9U"
    "VBSxvLlKRA0xtjnCWGyU2d1ZNMNCdIpCfo0joOxpMSJ8BVTAcmjHjbjos661t5QLS5EMirzB"
    "lh5DswwEnJiI5EwLLZdDlC1Rr8n16StWmCgRIC3yhPF3b9dGJMtCM1K4hBJypoCBhSYYpEWN"
    "HXOPcHSXb/MJ2pKdRYicBOoBZx6gah9zd1+PR4IDA/X5b+aiOI5prMd22IlCtVJJt3mWM6X9"
    "9J3opbaqWm0abpIAGRDzAJNXzHyp23rU1Oy5ufF+mwZnC9e9/QRKevD5vbiL3bhcMt5iH6LX"
    "KCKAkynSgJlnu5ExFrj3bDQ8NLR8xdPX0UtjbQNutwfdoTGVmWB6c5KJ2Hh6Y3lv3g6gD5D2"
    "ARaThGjhYVbO3F7IfmJk6QUzqWkzsa2ECPOZJbaJomOgACu2ldavUfZTSw9PUVFYJMw6GhnS"
    "QAxYA1aBTWDXDlTyMAAgH2gC+oECe2ENiANJ2/sMYGA/1+8A7EWf3VOBNJA9OPU/JfwBfkQ/"
    "AU/kDpSM2ckCAAAAAElFTkSuQmCC")

#----------------------------------------------------------------------
_book_blue = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAn9J"
    "REFUOI2NkztMFGEQx3+77Hnc3e4dRwSJPETeBEwk8lIphEITqaAyxkQ7GitjLEyMrY2thZ2F"
    "DQUFCSpGEiNBjJHwChHlkRM45Y7Hcdw+WW7XwoMgxMe/msnM/DLzfTMCf5dwwHb/lSBAr8g1"
    "oQZVbMYnNyEHz2Fu67y6f5PEWAywjgJuL3cg2FdRvI14jQbwBRF9oBuImDiuBNNDLxnouQf2"
    "3GFIVlHXnYkChfZUcXGpP77uPSNbNAc1Oms9dNf5WU1axMivJLtcYWlwEkgBzh5AXNkyBU9u"
    "LvnrUcy0QHtdgJpShRyfRMKAsyUySBJUXrxBw4Me4CQg7XdA/pVLdkt9uXdhCS0QYjWmMhNL"
    "0zelMTyRZPLLBpgauGkBpaiZHc8am+PzgA64WXiqN0y57Hp2dbmgrCwQUSUSSQssC9wdSNuw"
    "u/vLd1wRX+l5jO1F1PkIYIhMPxxm9O2LuCNiih7C0g7YFti7YNlgpUG1Ia5DdIOGQsMvCOl6"
    "4DRwTAJ0vn54xLvKy8mOVk945D3YPkgYoKY4EUzQWqhxoT2Llio/RcUFesWz114gAIgS4PDj"
    "yRjTtc93K2puGYvjNOebtNVD4ymRUEhGCYWQAzLhHAXNV+CnsPsY0T4DcPZe0+T78GMG8ro7"
    "C/qDTTV1lFVWEVQCmK6fNxEfI5Eshj5rBt8Gp3AEAQgD3j2AS6x3jry2p7pw/O5MXGZgQeBT"
    "xHFSq2tzqB9nSY5uoi/YuHYKWAI0wP19lXMaSsjr6sdWU2wOLaLNWqQ1A1gDosAysApsZRZK"
    "PQgA8AAVQBuQnSmIAhuAmvl7E0iTOa7DADKF4UxMBwxgZ3/U/5TwB/gR/QQ8K/3nl/ZkqAAA"
    "AABJRU5ErkJggg==")


Mondrian = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAHFJ"
    "REFUWIXt1jsKgDAQRdF7xY25cpcWC60kioI6Fm/ahHBCMh+BRmGMnAgEWnvPpzK8dvrFCCCA"
    "coD8og4c5Lr6WB3Q3l1TBwLYPuF3YS1gn1HphgEEEABcKERrGy0E3B0HFJg7C1N/f/kTBBBA"
    "+Vi+AMkgFEvBPD17AAAAAElFTkSuQmCC")

