return {
  autolayout=true,
  fileversioncreate="00.10",
  fileversionsave="01.02",
  nodes={
    {
      type="Start",
      children={
        {
          type="Selector",
          children={
            {
              type="Sequence",
              children={
                {
                  func="#condition|'a'|2",
                  type="Condition"
                },
                {
                  func="!globalaction",
                  type="Action"
                } 
              }
            },
            {
              type="Sequence",
              children={
                {
                  func="",
                  type="Condition"
                },
                {
                  func="",
                  type="Action"
                } 
              }
            } 
          }
        } 
      }
    } 
  },
  notes="note per il test tree\
su piu righe\
etc\
etc\
fine",
  title="test tree" 
}